version: '3.8'

services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: